spring:
  datasource:
    url: jdbc:mysql://localhost/springboot
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true